name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Build project (static)
        run: pnpm build

      - name: Verify static export output
        run: test -f out/index.html

      - name: Upload static export artifact
        uses: actions/upload-artifact@v4
        with:
          name: vetra-ui-static-export
          path: out/

      - name: Build project (dynamic)
        run: pnpm build:dynamic

      - name: Verify standalone server output
        run: test -f .next/standalone/server.js
